server:
  port:
    8083
  error:
    include-stacktrace: never
spring:
  data:
    mongodb:
      authentication-databse: ${MONGODB_AUTHENTICATION_DB}
      host: ${MONGODB_LOCAL_HOST}
      port: ${MONGODB_LOCAL_PORT}
      database: ${MONGODB_DISNEY_MEDIA_DB}
      username: ${MONGODB_DISNEY_USERNAME}
      password: ${MONGODB_DISNEY_PASSWORD}